listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = 128MB
log_timezone = 'Europe/Moscow'
timezone = 'Europe/Moscow'
datestyle = 'iso, mdy'
default_text_search_config = 'pg_catalog.russian'
lc_messages = 'en_US.utf8'