DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS oauth_accounts;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS users;
DROP TYPE  IF EXISTS user_status;
DROP TYPE  IF EXISTS user_role;
DROP EXTENSION IF EXISTS "uuid-ossp";