apiVersion: v1
kind: Secret
metadata:
  name: realty-secrets
  namespace: realty
type: Opaque
stringData:
  POSTGRES_PASSWORD: "tr134sdfWE"
  JWT_SECRET: "supersecretkey_change_in_prod"
  MINIO_ROOT_PASSWORD: "minioadmin123"
  DATABASE_URL: "postgres://usr:tr134sdfWE@postgres:5432/lets_goto_it?sslmode=disable"
